name: Run NotaGen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-notagen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip wget python3-pip

      - name: Install Python Dependencies (if available)
        run: |
          if [ -f "requirements.txt" ]; then
            pip3 install -r requirements.txt
          else
            echo "No requirements.txt found, skipping Python dependencies installation."
          fi

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.5-bin.zip -P /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-8.5-bin.zip
          echo "export PATH=\$PATH:/opt/gradle/gradle-8.5/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Build and Run NotaGen
        run: |
          if [ -f "build.gradle" ]; then
            gradle build
            gradle run
          elif [ -f "main.py" ]; then
            python3 main.py
          else
            echo "No recognized entry point found."
          fi
